before_install:
- openssl aes-256-cbc -K $encrypted_b295e0f06079_key -iv $encrypted_b295e0f06079_iv
  -in gaekey.json.enc -out gaekey.json -d

deploy:
  provider: gae
  keyfile: gaekey.json
  project: deploying-to-257-78109e23
  on:
    branch: main
